/*
 *  This file is part of SimpleChess.
 *  Copyright (C) 2016, Vladimir Fekete
 *
 *  SimpleChess is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SimpleChess is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
*/

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Vladimir Fekete
 */
public class HomeCard extends javax.swing.JPanel implements ICard {

    /**
     * Creates new form HomePanel
     */
    public HomeCard(IHomeCardAction actionTarget) {
        initComponents();
        this.actionTarget = actionTarget;
    }

    //
    //  ICard interface
    //
    @Override
    final public String getName() {
        return "HomeCard";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeText = new javax.swing.JLabel();
        logoText = new javax.swing.JLabel();
        newGame = new javax.swing.JButton();
        loadGame = new javax.swing.JButton();
        logo2Text = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setName(""); // NOI18N

        welcomeText.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        welcomeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeText.setText("Simple Chess");

        logoText.setFont(new java.awt.Font("Dialog", 0, 56)); // NOI18N
        logoText.setText("♟♞♝♜♛♚");
        logoText.setDoubleBuffered(true);

        newGame.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newGame.setText("NEW GAME");
        newGame.setBorderPainted(false);
        newGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameActionPerformed(evt);
            }
        });

        loadGame.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loadGame.setText("LOAD GAME");
        loadGame.setBorderPainted(false);
        loadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameActionPerformed(evt);
            }
        });

        logo2Text.setFont(new java.awt.Font("Dialog", 0, 96)); // NOI18N
        logo2Text.setText("♔♕♖♗♘♙");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(119, 119, 119)
                            .addComponent(logoText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(97, 97, 97))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(108, 108, 108)
                            .addComponent(newGame, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(87, 87, 87)
                            .addComponent(loadGame)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(welcomeText))
                            .addComponent(logo2Text))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(logoText)
                .addGap(49, 49, 49)
                .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadGame)
                    .addComponent(newGame))
                .addGap(67, 67, 67)
                .addComponent(logo2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameActionPerformed
        if (actionTarget != null) {
            actionTarget.startNewGame();
        }
    }//GEN-LAST:event_newGameActionPerformed

    private void loadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameActionPerformed
        JFileChooser chooser = new JFileChooser();

        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Simple chess game (*.scgame)", "scgame"));
        chooser.setAcceptAllFileFilterUsed(false);

        if (actionTarget != null && chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            actionTarget.loadGameFromFile(chooser.getSelectedFile().toPath());
        }
    }//GEN-LAST:event_loadGameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loadGame;
    private javax.swing.JLabel logo2Text;
    private javax.swing.JLabel logoText;
    private javax.swing.JButton newGame;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
    private IHomeCardAction actionTarget;

}
